// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpykqpprbzqbvedwugap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZweWtxcHByYnpxYnZlZHd1Z2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2MjM1OTYsImV4cCI6MjA4NTE5OTU5Nn0.EFByNlKIkZ1wUaYCnHtX4Eaw6vmHgl7C8iknsiE8Yic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});